In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.svm import SVC
from sklearn import metrics , model_selection , preprocessing
from IPython.display import Image ,display
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
data=pd.read_csv("D:\\tala\\carsdata.csv")
data.head()

Model  Engine SC/Turbo   Weight Fuel Economy Fast
0    M1   Small       No  Average         Good   No
1    M2   Small       No    Light      Average   No
2    M3   Small      Yes  Average          Bad  Yes
3    M4  Medium       No    Heavy          Bad  Yes
4    M5   Large       No  Average          Bad  Yes

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Model         15 non-null     object
 1   Engine        15 non-null     object
 2   SC/Turbo      15 non-null     object
 3   Weight        15 non-null     object
 4   Fuel Economy  15 non-null     object
 5   Fast          15 non-null     object
dtypes: object(6)
memory usage: 848.0+ bytes


# preprocessing

In [4]:
data=data.drop(["Model"] , axis=1)
data.head()

Engine SC/Turbo   Weight Fuel Economy Fast
0   Small       No  Average         Good   No
1   Small       No    Light      Average   No
2   Small      Yes  Average          Bad  Yes
3  Medium       No    Heavy          Bad  Yes
4   Large       No  Average          Bad  Yes

In [5]:
data["Engine"].dtype

dtype('O')

In [6]:
#changing to being categorical
data.Engine=pd.Categorical(data.Engine)
data["re_Engine"]=data["Engine"].cat.codes


In [7]:
data["re_Engine"].dtype

dtype('int8')

In [8]:
data["SC/Turbo"]=pd.Categorical(data["SC/Turbo"])
data["re_SC/Turbo"]=data["SC/Turbo"].cat.codes

data.Weight=pd.Categorical(data.Weight)
data["re_Weight"]=data["Weight"].cat.codes

data["Fuel Economy"]=pd.Categorical(data["Fuel Economy"])
data["re_Fuel Economy"]=data["Fuel Economy"].cat.codes

data.Fast=pd.Categorical(data.Fast)
data["re_Fast"]=data["Fast"].cat.codes

In [9]:
data=data.drop(["Engine","SC/Turbo","Weight","Fuel Economy","Fast"] , axis=1)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   re_Engine        15 non-null     int8 
 1   re_SC/Turbo      15 non-null     int8 
 2   re_Weight        15 non-null     int8 
 3   re_Fuel Economy  15 non-null     int8 
 4   re_Fast          15 non-null     int8 
dtypes: int8(5)
memory usage: 203.0 bytes


In [11]:
data.head()

re_Engine  re_SC/Turbo  re_Weight  re_Fuel Economy  re_Fast
0          2            0          0                2        0
1          2            0          2                0        0
2          2            1          0                1        1
3          1            0          1                1        1
4          0            0          0                1        1

# detecting inputs and target

In [12]:
x=data.drop(["re_Fast"] , axis=1)
y=data["re_Fast"]

# splitting our data to train and test

In [13]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train ,y_test=train_test_split(x , y , test_size=0.2 , random_state=42)

In [14]:
x_train.shape  , x_test.shape

((12, 4), (3, 4))

# machine learning algorithems
1_decision tree

2_random forest

3_SVM

decision tree

In [15]:
dt=tree.DecisionTreeClassifier()

In [16]:
dt.fit(x_train , y_train)

DecisionTreeClassifier()

In [17]:
y_pred=dt.predict(x_test)

In [18]:
y_pred

array([1, 0, 0], dtype=int8)

In [19]:
y_test

9     1
11    0
0     0
Name: re_Fast, dtype: int8

# metrics evaluation

In [20]:
accuracy=metrics.accuracy_score(y_test , y_pred)
print("accuracy is :  {}".format(accuracy))

accuracy is :  1.0


# random forest

In [22]:
rf=RandomForestClassifier(n_estimators=10) #how mant trees(models) do you need?
rf.fit(x_train ,y_train)

RandomForestClassifier(n_estimators=10)

In [24]:
y_rf_pred=rf.predict(x_test)

In [25]:
y_rf_pred

array([1, 0, 0], dtype=int8)

# metrics evaluation

In [26]:
accuracy_rf=metrics.accuracy_score(y_test , y_rf_pred)
print("accuracy is :  {}".format(accuracy_rf))

accuracy is :  1.0


# SVM

In [27]:
svm_model=svm.SVC()
svm_model.fit(x_train,y_train)

SVC()

In [29]:
y_svm_pred=svm_model.predict(x_test)

In [30]:
y_svm_pred

array([0, 0, 0], dtype=int8)

# metrics_evaluation

In [31]:
accuracy_svm=metrics.accuracy_score(y_test , y_svm_pred)
print("accuracy is :  {}".format(accuracy_svm))

accuracy is :  0.6666666666666666
